### ISSUE TITLE
ToolStripButton placed after ToolStripComboBox not found in WinForms app

### ISSUE THREAD

**Issue by valerystartsev** [2gis/Winium.Cruciatus#47]
Can't find button placed after ToolStripComboBox :(

Visual UI Automation Verify & Inspect tools shows both buttons in the tree :)
UISpy - does not show button2  :(

Test code:
        [TestMethod]
        public void TestMethod2()
        {
            var app = new Winium.Cruciatus.Application(@"path to simple test application"); 
            app.Start();

            var winFinder = By.Name("MainTestWindow").AndType(ControlType.Window);
            var win = Winium.Cruciatus.CruciatusFactory.Root.FindElement(winFinder);
            var menu = win.FindElementByUid("toolStrip1").ToMenu();
            var button1 = menu.FindElementByName("btn 1");
            button1.Click();
            var button2 = menu.FindElementByName("btn 2");
            button2.Click();

            app.Kill();
            //app.Close();
        }

Simple Test application code:
    public class Form1 : Form
    {
        private ToolStrip toolStrip1;
        private ToolStripButton button1;
        private ToolStripButton button2;
        private ToolStripComboBox drop1;
        

        public Form1()
        {
            InitializeComponent();
            this.Text = "MainTestWindow";
        }
        private void InitializeComponent()
        {
            toolStrip1 = new System.Windows.Forms.ToolStrip();
            toolStrip1.GripStyle = ToolStripGripStyle.Hidden; // no matter
            toolStrip1.Name = "toolStrip1";
            toolStrip1.Text = "toolStrip 1";
            button1 = new ToolStripButton("one 1");
            button1.Name = "btn1";
            button1.Text = "btn 1";
            button2 = new ToolStripButton("two 2");
            button2.Name = "btn2";
            button2.Text = "btn 2";
            drop1 = new ToolStripComboBox("combo1");
            drop1.Name = "drop1";
            // Add items to the ToolStrip.
            toolStrip1.Items.Insert(0, button1);
            toolStrip1.Items.Insert(1, drop1);
            toolStrip1.Items.Insert(2, button2);
            drop1.Visible = true; // if true test fails, if false - test passes            
            Controls.Add(toolStrip1);   
        }
    }

**Comment by skyline-gleb** [comment]
Hi,
UISpy running as administrator?

**Comment by valerystartsev** [comment]
yes

**Comment by valerystartsev** [comment]
I've tried with an other tool Automation spy from http://www.automationspy.com/ - it also does not show  button2 in the tree

**Comment by valerystartsev** [comment]
in UISpy I have exception in attempts to navigate to last chield
Exception
Time Stamp : 10/2/2015 2:20 PM
Element : "combo box" ""
Name : TreeValidationException
Message : UI Automation tree navigation is broken. The parent of one of the descendants exist but the descendant is not the child of the parent
Stack Trace :    at UISpy.Base.Tree.BuildTree(AutomationElement element)
   at UISpy.Base.Tree.BuildRelatedTrees(Node existingNode)

**Comment by valerystartsev** [comment]
![uispy_exception](https://cloud.githubusercontent.com/assets/12845451/10245584/94fab3d8-6911-11e5-956c-6966666de077.PNG)

**Comment by skyline-gleb** [comment]
this test application? can you give me the source code?
p.s. кажется мы бы могли общаться по русски ))

**Comment by valerystartsev** [comment]
Да, тестовое winforms приложение простейшее :)
почти весь код в первом сообщении, там не хватает только кода из Main:
static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }
    }

сейчас приложу архив с кодом прииложения и теста для VS 2013

**Comment by skyline-gleb** [comment]
то что код минимальный увидел, но архивчик это будет прям супер, гораздо меньше затрат, для быстрого анализа

**Comment by valerystartsev** [comment]
хм, а как zip положить ?

**Comment by skyline-gleb** [comment]
да, zip в самый раз, можно прям прям на [email](mailto:g.golovin@2gis.ru)

**Comment by valerystartsev** [comment]
ушло на почту

**Comment by skyline-gleb** [comment]
точно ушло? не вижу ни во входящих ни в спаме (мало ли)

**Comment by valerystartsev** [comment]
продублировал отправку из gmail

**Comment by skyline-gleb** [comment]
Проблема в combobx-е, если он не последний. Получается ситуация, что combobox, добавленный в toolstrip, представляется в визуальном дереве двумя элементами, причем один в дереве выше остальных элементов и он корректен, а вот второй находится по порядку в том же месте где и в интерфейсе, и он выдаёт ошибку, из-за чего дальнейшее чтение дерева прерывается на уровне механизма UIAutomation, потому и не видно всех элементов, что следуют в интерфейса за combobox-ом. В скриншоте выше вся эта ситуация и прослеживается((
Да, проблема встречается в UISpy и Cruciatus всегда работал с ним заодно - видно через UISpy значит найдет Cruciatus, и при ошибках таже история. Однако VisualUIAVerifyNative видит элементы без проблем, нужно попробовать разобраться почему и можно ли решить проблему.
